name: MLOps CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-docker:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run Unit Tests
        run: pytest -q

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/cats-dogs-api:latest .

      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository }}/cats-dogs-api:latest

  deploy:

    needs: build-test-docker
    runs-on: ubuntu-latest

    permissions:
      packages: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull Image
        run: docker pull ghcr.io/${{ github.repository }}/cats-dogs-api:latest

      - name: Run Container
        run: |
          docker run -d -p 8000:8000 --name test-api ghcr.io/${{ github.repository }}/cats-dogs-api:latest
          sleep 10

      - name: Smoke Test - Health Endpoint
        run: curl --fail http://localhost:8000/health

      - name: Smoke Test - Prediction Endpoint
        run: |
          curl --fail -X POST "http://localhost:8000/predict" \
          -H "accept: application/json" \
          -H "Content-Type: multipart/form-data" \
          -F "file=@tests/assets/sample.jpg"

      - name: Stop Container
        run: docker stop test-api
